heat_template_version: 2013-05-23

description: Meghdoot Test App

parameters:
  Pool_Name:
    type: string
    label: Floating IP Pool
    description: Floating IP Pool Range from which the instance will get assigned
    default: venu
  SSH_Key:
    type: string
    label: SSH Key
    description: Public key from the machine from which you'd like to access the instance
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgbmnx2CL9IbekIHRZQkr47w1BpmRDt+6HaK7SqpgV+R4rzJJcoxQwiUYsCCgMOhEJ47vao7EZXjtL2Mm2T5OQinFN/Ron8Oq4MhCzq0HgLQfqJ20yRwZ8vWqXXjVzSkEXecydQ+GAyIAJaxIshy5JkC+2NOdcZXp4NEdxqFo0i88lZpLDISER+a7wzAisppQbirL3PoPD/7Z/yl64PZExKTwUqhVRNJf+Qkvp0tOLQZWMfs/pQoAx5mVgA4hQoCKh3IO8YBcErTXAKjXTKwm0TfepUxawEAImfl/5QWDFgFToPvAGTk3ovfUeK2wW/Xef7O6g/wAk+UBSPRAagwNt venum@invenum.corporate.thoughtworks.com

  Image_Name:
    type: string
    label: Image Name or ID
    description: An Ubuntu Cloud Image image already uploaded to OpenStack
    default: 86efb87f-814f-4071-ba8e-082eb807f223

resources:
  mango_app_init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        users:
        - name: ubuntu
          sudo: ALL=(ALL) NOPASSWD:ALL
          ssh-authorized-keys:
          - { get_param: SSH_Key }
  mango_db_script:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/sh
        apt-get install -y mongodb-server
        sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongodb.conf
        sudo service mongodb restart
  mango_app_script:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/sh
        apt-get install -y git
        apt-get install -y nodejs-legacy
        cd /home/ubuntu
        git clone https://github.com/asifrc/meghdoot-test-app.git
        meghdoot-test-app/node_modules/.bin/forever start meghdoot-test-app/bin/www
        sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
  mango_app:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: mango_app_init }
      - config: { get_resource: mango_db_script }
      - config: { get_resource: mango_app_script }
  mango_db:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: { get_resource: mango_app_init }
      - config: { get_resource: mango_db_script }
      
  mango_flavor:
    type: OS::Nova::Flavor
    properties:
      ram: 2048
      vcpus: 1
      disk: 20
  mango_keypair:
    type: OS::Nova::KeyPair
    properties:
      name: mango_from_box1
      public_key: { get_param: SSH_Key }
  mango_instance:
    type: OS::Nova::Server
    depends_on: [ mango_flavor, mango_keypair ]
    properties:
      name: meghdoot_instance
      flavor: { get_resource: mango_flavor }
      image: { get_param: Image_Name }
      key_name: { get_resource: mango_keypair }
      user_data_format: RAW
      user_data:
        get_resource: mango_app

  mango_floatingip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: Pool_Name }
  mango_ip_assoc:
    type: OS::Nova::FloatingIPAssociation
    depends_on: [ mango_instance ]
    properties:
      floating_ip: { get_resource: mango_floatingip }
      server_id: { get_resource: mango_instance }    
